---

- name: Configure EC2 instance
  hosts: webserver
  connection: ssh
  become: yes

  tasks:
  - name: Enable RHEL extras repository
    shell: yum-config-manager --enable rhel-7-server-extras-rpms

  - name: Enable AWS RHEL extras repository
    shell: yum-config-manager --enable rhui-REGION-rhel-server-extras
  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest

  - name: Install device-mapper-persistent-data
    yum:
      name: device-mapper-persistent-data
      state: latest

  - name: Install lvm2
    yum:
      name: lvm2
      state: latest

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    become: yes

  - name: Disable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docker-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0
    become: yes

  - name: Disable Docker Test repo
    ini_file:
      dest: /etc/yum.repos.d/docker-ce.repo
      section: 'docker-ce-test'
      option: enabled
      value: 0
    become: yes
  - name: Install containerd
    package:
      name: containerd.io-1.2.2-3.el7.x86_64
    become: yes

  - name: Install Docker
    package:
      name: docker-ce
      state: latest
    become: yes

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: yes

  - name: Add user ec2-user to docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
    become: yes
  - name: reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection
