---

- name: Configure EC2 instance
  hosts: webserver
  connection: ssh

  tasks:
  - name: Installing Curl Command
    command: sudo yum install curl -y
  - name: Restarting docker service
    command: sudo systemctl restart docker
  - name: copy Dockerfile to ec2 instance
    copy:
      src: Dockerfile
      dest: /home/ec2-user

  - name: copy index.html to ec2 instance
    copy:
      src: index.html
      dest: /home/ec2-user
  - name: Build docker image using Dockerfile
    shell: docker build -t angautam/nginx:v1 .
  - name: Run container with custom built docker image
    shell: docker run -dP --name mynginx -p 80:80 angautam/nginx:v1
  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
      url: http://localhost

# Check that a page returns a status 200 and fail if the word "Hello World" is not
# in the page contents.
  - uri:
      url: http://localhost
      return_content: yes
    register: this
    failed_when: "'Hello World' not in this.content"
